runtime: python39

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|css|png|jpg|svg|woff2?))
    static_files: build/\1
    upload: build/.*

  - url: /.*
    script: auto